// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FraudAlert struct {
	ID          int64              `json:"id"`
	AlertID     pgtype.Int4        `json:"alert_id"`
	UserID      uuid.UUID          `json:"user_id"`
	AlertReason string             `json:"alert_reason"`
	AlertLevel  pgtype.Int4        `json:"alert_level"`
	Slug        string             `json:"slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID       int64 `json:"id"`
	FromUser int64 `json:"from_user"`
	ToUser   int64 `json:"to_user"`
	// must be positive
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserWatch struct {
	ID          int64              `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	WatchReason string             `json:"watch_reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
