// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: rpc_create_user_watch.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserWatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WatchReason string `protobuf:"bytes,2,opt,name=watch_reason,json=watchReason,proto3" json:"watch_reason,omitempty"`
}

func (x *CreateUserWatchRequest) Reset() {
	*x = CreateUserWatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_user_watch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserWatchRequest) ProtoMessage() {}

func (x *CreateUserWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_user_watch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserWatchRequest.ProtoReflect.Descriptor instead.
func (*CreateUserWatchRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_user_watch_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserWatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserWatchRequest) GetWatchReason() string {
	if x != nil {
		return x.WatchReason
	}
	return ""
}

type CreateUserWatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserWatch *UserWatch `protobuf:"bytes,1,opt,name=userWatch,proto3" json:"userWatch,omitempty"`
}

func (x *CreateUserWatchResponse) Reset() {
	*x = CreateUserWatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_create_user_watch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserWatchResponse) ProtoMessage() {}

func (x *CreateUserWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_user_watch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserWatchResponse.ProtoReflect.Descriptor instead.
func (*CreateUserWatchResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_user_watch_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserWatchResponse) GetUserWatch() *UserWatch {
	if x != nil {
		return x.UserWatch
	}
	return nil
}

var File_rpc_create_user_watch_proto protoreflect.FileDescriptor

var file_rpc_create_user_watch_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x57, 0x61, 0x74, 0x63, 0x68, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x61, 0x74, 0x68, 0x65, 0x6d, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x73, 0x2f, 0x66, 0x72, 0x61,
	0x75, 0x64, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_create_user_watch_proto_rawDescOnce sync.Once
	file_rpc_create_user_watch_proto_rawDescData = file_rpc_create_user_watch_proto_rawDesc
)

func file_rpc_create_user_watch_proto_rawDescGZIP() []byte {
	file_rpc_create_user_watch_proto_rawDescOnce.Do(func() {
		file_rpc_create_user_watch_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_create_user_watch_proto_rawDescData)
	})
	return file_rpc_create_user_watch_proto_rawDescData
}

var file_rpc_create_user_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_user_watch_proto_goTypes = []interface{}{
	(*CreateUserWatchRequest)(nil),  // 0: pb.CreateUserWatchRequest
	(*CreateUserWatchResponse)(nil), // 1: pb.CreateUserWatchResponse
	(*UserWatch)(nil),               // 2: pb.UserWatch
}
var file_rpc_create_user_watch_proto_depIdxs = []int32{
	2, // 0: pb.CreateUserWatchResponse.userWatch:type_name -> pb.UserWatch
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_user_watch_proto_init() }
func file_rpc_create_user_watch_proto_init() {
	if File_rpc_create_user_watch_proto != nil {
		return
	}
	file_user_watch_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_create_user_watch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserWatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_create_user_watch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserWatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_create_user_watch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_user_watch_proto_goTypes,
		DependencyIndexes: file_rpc_create_user_watch_proto_depIdxs,
		MessageInfos:      file_rpc_create_user_watch_proto_msgTypes,
	}.Build()
	File_rpc_create_user_watch_proto = out.File
	file_rpc_create_user_watch_proto_rawDesc = nil
	file_rpc_create_user_watch_proto_goTypes = nil
	file_rpc_create_user_watch_proto_depIdxs = nil
}
